# Generated by Django 3.2.11 on 2022-03-25 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturebookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
