# Generated by Django 3.2.11 on 2022-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0002_lecturebookmark_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturebookmark',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
