# Generated by Django 3.2.11 on 2022-03-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0003_alter_lecturebookmark_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturebookmark',
            old_name='lecture',
            new_name='lecture_url',
        ),
    ]
