# Generated by Django 3.2.11 on 2022-03-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wm', '0004_rename_lecture_lecturebookmark_lecture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturebookmark',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
